import * as fs from "node:fs";
import { Cookie, CookieJar } from "tough-cookie";
import { logger } from "./logger";

/**
 * Represents a parsed Netscape cookie entry.
 */
interface NetscapeCookie {
  domain: string;
  includeSubdomains: boolean;
  path: string;
  secure: boolean;
  expires: number;
  name: string;
  value: string;
  httpOnly: boolean;
}

/**
 * Parse a Netscape format cookie file into an array of cookie objects.
 * Format: domain<TAB>includeSubdomains<TAB>path<TAB>secure<TAB>expires<TAB>name<TAB>value
 *
 * Lines starting with # are comments, except #HttpOnly_ prefix indicates HttpOnly flag.
 */
export function parseNetscapeCookieFile(filePath: string): NetscapeCookie[] {
  if (!fs.existsSync(filePath)) {
    throw new Error(`Cookie file not found: ${filePath}`);
  }

  const content = fs.readFileSync(filePath, "utf-8");
  const lines = content.split(/\r?\n/);
  const cookies: NetscapeCookie[] = [];

  for (const rawLine of lines) {
    let line = rawLine.trim();

    // Skip empty lines
    if (!line) continue;

    // Check for HttpOnly prefix
    let httpOnly = false;
    if (line.startsWith("#HttpOnly_")) {
      httpOnly = true;
      line = line.substring(10); // Remove "#HttpOnly_" prefix
    } else if (line.startsWith("#")) {
      // Regular comment line, skip
      continue;
    }

    // Support both tab-separated (standard) and space-separated (Cookie-Editor) formats
    let parts = line.split("\t");
    if (parts.length < 7) {
      // Try splitting by whitespace (for Cookie-Editor exports that use spaces)
      parts = line.split(/\s+/);
    }
    if (parts.length < 7) {
      logger.warn(`Skipping malformed cookie line: ${line}`);
      continue;
    }

    const [domain, includeSubdomains, path, secure, expires, name, value] =
      parts;

    cookies.push({
      domain,
      includeSubdomains: includeSubdomains === "TRUE",
      path,
      secure: secure === "TRUE",
      expires: Number.parseInt(expires, 10),
      name,
      value,
      httpOnly,
    });
  }

  // Validate SESSDATA exists (required for authentication)
  const hasSessdata = cookies.some((c) => c.name === "SESSDATA");
  if (!hasSessdata) {
    throw new Error(
      `Cookie file ${filePath} does not contain SESSDATA. Authentication will fail.`,
    );
  }

  logger.info(`Loaded ${cookies.length} cookies from ${filePath}`);
  return cookies;
}

/**
 * Create a CookieJar from an array of parsed Netscape cookies.
 */
export function createCookieJarFromNetscape(
  cookies: NetscapeCookie[],
): CookieJar {
  const jar = new CookieJar();

  for (const c of cookies) {
    try {
      // Determine protocol based on secure flag
      const protocol = c.secure ? "https" : "http";
      // Build URL for the cookie
      const url = `${protocol}://${
        c.domain.startsWith(".") ? c.domain.substring(1) : c.domain
      }${c.path}`;

      const cookie = new Cookie({
        key: c.name,
        value: c.value,
        domain: c.domain,
        path: c.path,
        secure: c.secure,
        httpOnly: c.httpOnly,
        expires: c.expires > 0 ? new Date(c.expires * 1000) : "Infinity",
        hostOnly: !c.includeSubdomains,
      });

      jar.setCookieSync(cookie, url);
    } catch (error) {
      logger.warn(`Failed to add cookie ${c.name}: ${error}`);
    }
  }

  return jar;
}

/**
 * Write a CookieJar back to a Netscape format cookie file.
 */
export function writeCookieJarToNetscape(
  jar: CookieJar,
  filePath: string,
): void {
  try {
    // Use serializeSync to get all cookies from the jar (avoids hardcoding domains)
    const serialized = jar.serializeSync();
    if (!serialized) {
      logger.warn(`Failed to serialize cookie jar for ${filePath}`);
      return;
    }
    const uniqueCookies = serialized.cookies;

    const lines: string[] = [
      "# Netscape HTTP Cookie File",
      "# http://curl.haxx.se/rfc/cookie_spec.html",
      "# This file was generated by hantang-dynamic",
    ];

    for (const c of uniqueCookies) {
      const prefix = c.httpOnly ? "#HttpOnly_" : "";
      const domain = (c.domain as string) || ".bilibili.com";
      const includeSubdomains = c.hostOnly ? "FALSE" : "TRUE";
      const path = (c.path as string) || "/";
      const secure = c.secure ? "TRUE" : "FALSE";
      // SerializedCookie.expires is string (ISO) or undefined
      let expires = "0";
      if (c.expires && c.expires !== "Infinity") {
        const expDate = new Date(c.expires as string);
        if (!Number.isNaN(expDate.getTime())) {
          expires = Math.floor(expDate.getTime() / 1000).toString();
        }
      }
      const name = c.key;
      const value = c.value;

      lines.push(
        `${prefix}${domain}\t${includeSubdomains}\t${path}\t${secure}\t${expires}\t${name}\t${value}`,
      );
    }

    fs.writeFileSync(filePath, `${lines.join("\n")}\n`, "utf-8");
    logger.debug(`Persisted ${uniqueCookies.length} cookies to ${filePath}`);
  } catch (error) {
    logger.warn(`Failed to persist cookies to ${filePath}: ${error}`);
  }
}

/**
 * Extract a specific cookie value from the jar by name and optional domain pattern.
 */
export function getCookieValue(
  jar: CookieJar,
  name: string,
  domainPattern = "bilibili.com",
): string | null {
  try {
    const cookies = jar.getCookiesSync(`https://${domainPattern}`, {
      allPaths: true,
    });
    const cookie = cookies.find((c) => c.key === name);
    return cookie?.value ?? null;
  } catch {
    return null;
  }
}
