name: Build and Package

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      # Install dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm run build

      - name: Package project with pkg
        run: pnpm run package

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: bilibili-dynamic-subscribe-linux
          path: dist/executables/index-linux

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: bilibili-dynamic-subscribe-macos
          path: dist/executables/index-macos

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: bilibili-dynamic-subscribe-windows
          path: dist/executables/index-win.exe

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}
