name: Build and Package

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: win
            arch: x64
            duckdb_lib_name: duckdb.dll
            start: start.bat
          - os: ubuntu-latest
            platform: linux
            arch: x64
            duckdb_lib_name: libduckdb.so
            start: start.sh
          - os: ubuntu-22.04-arm
            platform: linux
            arch: arm64
            duckdb_lib_name: libduckdb.so
            start: start.sh
          - os: macos-latest
            platform: macos
            arch: arm64
            duckdb_lib_name: libduckdb.dylib
            start: start.sh

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - uses: MOZGIII/install-ldid-action@v1
        if: ${{ matrix.platform == 'macos' }}
        with:
          tag: v2.1.5-procursus7

      - name: Build project
        run: pnpm run build

      - name: Package project with pkg
        run: pnpm run package

      - name: Renaming and moving artifacts
        run: |
          if [ "${{ matrix.platform }}" = "win" ]; then
            mv dist/executables/index-win-x64.exe dist/bilibili-dynamic-subscribe-${{ matrix.platform }}-${{ matrix.arch }}.exe
          else
            mv dist/executables/index-${{ matrix.platform }}-${{ matrix.arch }} dist/bilibili-dynamic-subscribe-${{ matrix.platform }}-${{ matrix.arch }}
          fi

      - name: Prepare distribution files
        run: |
          cp .env.example dist/.env.example
          cp README.md dist/README.md
          cp start.* dist/

      - name: Create platform bundle
        run: |
          cd dist
          zip -r "bundle-${{ matrix.platform }}-${{ matrix.arch }}.zip" bilibili-dynamic-subscribe-${{ matrix.platform }}-${{ matrix.arch }} .env.example README.md "${{ matrix.start }}" duckdb.node "${{ matrix.duckdb_lib_name }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: dist/bundle-${{ matrix.platform }}-${{ matrix.arch }}.zip
          name: bilibili-dynamic-subscribe-${{ matrix.platform }}-${{ matrix.arch }}

  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v4
      - name: Publish Release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: "true"
        with:
          artifacts: "bundle-linux-x64.zip,bundle-linux-arm64.zip,bundle-macos-arm64.zip,bundle-win-x64.exe"
