name: Build and Package

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] # Run on both Linux and Windows
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      # Install dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm run build

      - name: Remove Development Dependencies but keep pkg
        run: pnpm prune --prod && pnpm install -g @yao-pkg/pkg

      - name: Package project with pkg
        run: pkg . --out-path dist/executables --targets node20-win-x64,node20-linux-x64   --compress GZip

      # Upload the packaged executables as artifacts
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bilibili-video-tracker-${{ matrix.os }}
          path: dist/executables/bilibili-video-tracker-${{ matrix.os == 'windows-latest' && 'win' || 'linux' }}.exe
