name: Build and Package

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm run build

      - name: Package project with pkg
        run: pnpm run package

      - name: Renaming and moving artifacts
        run: |
          mv dist/executables/index-linux dist/bilibili-dynamic-subscribe-linux
          mv dist/executables/index-macos dist/bilibili-dynamic-subscribe-macos
          mv dist/executables/index-win.exe dist/bilibili-dynamic-subscribe-win.exe

      - name: Prepare distribution files
        run: |
          cp .env.example dist/.env.example
          cp README.md dist/README.md
          cp start.* dist/

      - name: Create platform bundles
        run: |
          cd dist
          for platform in linux macos win; do
            case $platform in
              linux)
                bin="bilibili-dynamic-subscribe-linux"
                start="start.sh"
                lib="libduckdb.so"
                ;;
              macos)
                bin="bilibili-dynamic-subscribe-macos"
                start="start.sh"
                lib="libduckdb.dylib"
                ;;
              win)
                bin="bilibili-dynamic-subscribe-win.exe"
                start="start.bat"
                lib="duckdb.dll"
                ;;
            esac
            zip -r "bundle-$platform.zip" "$bin" .env.example README.md "$start" duckdb.node "$lib"
          done
      
      - name: Upload artifacts for linux
        uses: actions/upload-artifact@v4
        with:
          path: dist/bundle-linux.zip
          name: bilibili-dynamic-subscribe-linux
      
      - name: Upload artifacts for macos
        uses: actions/upload-artifact@v4
        with:
          path: dist/bundle-macos.zip
          name: bilibili-dynamic-subscribe-macos

      - name: Upload artifacts for windows
        uses: actions/upload-artifact@v4
        with:
          path: dist/bundle-win.zip
          name: bilibili-dynamic-subscribe-win
        
      - name: Publish Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: "true"
        with:
          artifacts: "dist/bundle-*.zip"
