name: Build and Package

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: win
            arch: x64
            ext: .exe
            start: start.bat
          - os: ubuntu-latest
            platform: linux
            arch: x64
            start: start.sh
          - os: ubuntu-22.04-arm
            platform: linux
            arch: arm64
            start: start.sh
          - os: macos-latest
            platform: macos
            arch: arm64
            start: start.sh

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - uses: MOZGIII/install-ldid-action@v1
        if: ${{ matrix.platform == 'macos' }}
        with:
          tag: v2.1.5-procursus7

      - name: Build project
        run: pnpm run build

      - name: Package project with pkg
        run: pnpm run package

      - name: Renaming and moving artifacts
        run: |
          mv dist/executables/index-${{ matrix.platform }}-${{ matrix.arch }}${{ matrix.ext }} dist/bilibili-dynamic-subscribe-${{ matrix.platform }}-${{ matrix.arch }}${{ matrix.ext }}
          rm -r dist/executables

      - name: Prepare distribution files
        run: |
          cp .env.example dist/.env.example
          cp README.md dist/README.md

      - name: Write start script
        if: ${{ matrix.platform != 'win' }}
        run: |
          echo '#!/bin/bash
          if [ ! -f "$(dirname "$0")/.env" ]; then
          echo "Error: .env file not found!"
          echo "Please create a .env file with your configuration"
          cp "$(dirname "$0")/.env.example" "$(dirname "$0")/.env"
          exit 1
          fi
          exec "$(dirname "$0")/bilibili-dynamic-subscribe-${{ matrix.platform }}-${{ matrix.arch }}" "$@"' > dist/${{ matrix.start }}
          chmod +x dist/${{ matrix.start }}
          cp dist/${{ matrix.start }} dist/start

      - name: Write start script for Windows
        if: ${{ matrix.platform == 'win' }}
        run: |
          echo '@echo off
          if not exist ".env" (
            echo Error: .env file not found!
            echo Please create a .env file with your configuration
            copy ".env.example" ".env"
            exit /b 1
          )
          start "" /B "bilibili-dynamic-subscribe-${{ matrix.platform }}-${{ matrix.arch }}.exe" %*' > dist/start.bat

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bilibili-dynamic-subscribe-${{ matrix.platform }}-${{ matrix.arch }}
          path: dist/*

  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v4
      - name: Publish Release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: "true"
        with:
          artifacts: bilibili-dynamic-subscribe-*
